name: My First Github Action
on: [push]
jobs:
  build-app:                                #name of the jobs
    runs-on: ubuntu-latest                          #name of image where this job is going to execute
    steps:                                          #defining the steps
      - uses: actions/checkout@v2                     #executing the steps.
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8.0.312+7'
      - run: mvn clean install
      - run: bash ${{secrets.AWS_Bucket_Name}} ${{secrets.mavenfilepath}} ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} {{secrets.mavenfile}}
      