name: My First Github Action
on: [push]
jobs:
  build-app:                                #name of the jobs
    runs-on: ubuntu-latest                          #name of image where this job is going to execute
    steps:                                          #defining the steps
      - uses: actions/checkout@v2                     #executing the steps.
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8.0.312+7'
      - run: mvn clean install
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
            version: 2     # default
            verbose: false # default
            arch: amd64    # allowed values: amd64, arm64
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
         run: |
              aws s3 cp target/demo-0.0.1-SNAPSHOT.war s3://githubdemobucket/
              
      