name: My First Github Action
on: [push]
jobs:
  build-app:                                #name of the jobs
    runs-on: ubuntu-latest                          #name of image where this job is going to execute
    steps:                                          #defining the steps
      - uses: actions/checkout@v2                     #executing the steps.
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8.0.312+7'
      - run: mvn clean install

      - name: Deploy to my ec2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "target/demo-0.0.1-SNAPSHOT.war"
          REMOTE_HOST: "ec2-65-2-78-183.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/opt"