name: My First Github Action
on: [push]
jobs:
  build-app:                                #name of the jobs
    runs-on: ubuntu-latest                          #name of image where this job is going to execute
    steps:                                          #defining the steps
      - uses: actions/checkout@v2                     #executing the steps.
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8.0.312+7'
      - run: mvn clean install
      - name: copy files to ec2
        uses: appleboy/scp-action@master
        with:
          host: 65.2.78.183
          username: githubaction
          password: githubaction
          port: 22
          source: "target/demo-0.0.1-SNAPSHOT.war"
          target: "/tmp"
      - name: Deploy in ec2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USERNAME  }}
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
              cd /tmp && 
              cd target && 
              mv demo-0.0.1-SNAPSHOT.war /opt && 
              touch example.txt