name: My First Github Action
on: [push]
jobs:
  build-app:                                #name of the jobs
    runs-on: ubuntu-latest                          #name of image where this job is going to execute
    steps:                                          #defining the steps
      - uses: actions/checkout@v2                     #executing the steps.
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8.0.312+7'
      - run: mvn clean install

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo su -
            cd /tmp/s3test
            wget https://deploymentbucketself.s3.ap-south-1.amazonaws.com/codedeploy.zip
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}